=== topcoder-platform/tcc-cronos/ball/Forums_0.3/conf/com/orpheus/game/server/ValidationConfiguration.dtd
<?xml version="1.0" encoding="UTF-8"?><!--DTD generated by XMLSPY v2004 rel. 4 U (http://www.xmlspy.com)--><!ELEMENT validation (global, formset)><!ELEMENT global (constant*)><!ELEMENT formset (form*)><!ELEMENT constant (constant-name, constant-value)><!ELEMENT form (formLevelValidation*, associativeValidators, elements)><!ATTLIST form	name CDATA #REQUIRED><!ELEMENT constant-name (#PCDATA)><!ELEMENT constant-value (#PCDATA)><!ELEMENT formLevelValidation EMPTY><!ATTLIST formLevelValidation	validator CDATA #REQUIRED><!ELEMENT associativeValidators (validator*)><!ELEMENT elements (element*)><!ELEMENT validator (component*, associativeMessage)><!ATTLIST validator	name CDATA #REQUIRED	relationship CDATA #REQUIRED	operandsNumber CDATA #IMPLIED><!ELEMENT element (message)><!ATTLIST element	name CDATA #REQUIRED	pattern CDATA #REQUIRED><!ELEMENT component EMPTY><!ATTLIST component	name CDATA #REQUIRED><!ELEMENT associativeMessage EMPTY><!ATTLIST associativeMessage	nlsid CDATA #REQUIRED	isKey CDATA #REQUIRED><!ELEMENT message EMPTY><!ATTLIST message	nlsid CDATA #REQUIRED	isKey CDATA #REQUIRED>

=== topcoder-platform/tcc-cronos/ball/Forums_0.3/conf/com/orpheus/game/server/FormValidation.xml
<?xml version="1.0" ?>
<!DOCTYPE validation SYSTEM "ValidationConfiguration.dtd">
<validation>
    <global/>
    <formset>
        <form name="loginForm">
            <formLevelValidation validator="Username"/>
            <formLevelValidation validator="Password"/>
            <associativeValidators>
                <validator name="Username" relationship="AND">
                    <component name="username"/>
                    <associativeMessage nlsid="Username is required" isKey="false"/>
                </validator>
                <validator name="Password" relationship="AND">
                    <component name="password"/>
                    <associativeMessage nlsid="Password is required" isKey="false"/>
                </validator>
            </associativeValidators>
            <elements>
                <element name="username" pattern="[[\w]*[\W]*]+">
                    <message nlsid="Username is required" isKey="false"/>
                </element>
                <element name="password" pattern="[[\w]*[\W]*]+">
                    <message nlsid="Password is required" isKey="false"/>
                </element>
            </elements>
        </form>
        <form name="retrievePasswordForm">
            <formLevelValidation validator="Email"/>
            <associativeValidators>
                <validator name="Email" relationship="AND">
                    <component name="email"/>
                    <associativeMessage nlsid="Email address is required" isKey="false"/>
                </validator>
            </associativeValidators>
            <elements>
                <element name="email" pattern="[[\w]*[\W]*]+">
                    <message nlsid="Email address is required" isKey="false"/>
                </element>
            </elements>
        </form>
        <form name="joinGameForm">
            <formLevelValidation validator="TOS"/>
            <associativeValidators>
                <validator name="TOS" relationship="AND">
                    <component name="agree"/>
                    <associativeMessage nlsid="You must accept terms and conditions defined above" isKey="false"/>
                </validator>
            </associativeValidators>
            <elements>
                <element name="agree" pattern="[[\w]*[\W]*]+">
                    <message nlsid="You must accept terms and conditions defined above" isKey="false"/>
                </element>
            </elements>
        </form>
        <form name="rejectForm">
            <formLevelValidation validator="Reason"/>
            <formLevelValidation validator="Message"/>
            <associativeValidators>
                <validator name="Reason" relationship="AND">
                    <component name="rejectReason"/>
                    <associativeMessage nlsid="Reason is required" isKey="false"/>
                </validator>
                <validator name="Message" relationship="AND">
                    <component name="rejectMessage"/>
                    <associativeMessage nlsid="Message is required" isKey="false"/>
                </validator>
            </associativeValidators>
            <elements>
                <element name="rejectReason" pattern="[[\w]*[\W]*]+">
                    <message nlsid="Reason is required" isKey="false"/>
                </element>
                <element name="rejectMessage" pattern="[[\w]*[\W]*]+">
                    <message nlsid="Message is required" isKey="false"/>
                </element>
            </elements>
        </form>
        <form name="createGameStep1">
            <formLevelValidation validator="Keys"/>
            <formLevelValidation validator="Blocks"/>
            <associativeValidators>
                <validator name="Keys" relationship="AND">
                    <component name="keyCount"/>
                    <associativeMessage nlsid="Number of keys is either missing or does not represent a number" isKey="false"/>
                </validator>
                <validator name="Blocks" relationship="AND">
                    <component name="blockCount"/>
                    <associativeMessage nlsid="Number of blocks is either missing or does not represent a number" isKey="false"/>
                </validator>
            </associativeValidators>
            <elements>
                <element name="keyCount" pattern="[\d]+">
                    <message nlsid="Number of keys is either missing or does not represent a number" isKey="false"/>
                </element>
                <element name="blockCount" pattern="[\d]+">
                    <message nlsid="Number of blocks is either missing or does not represent a number" isKey="false"/>
                </element>
            </elements>
        </form>
        <form name="placeBidForm">
            <formLevelValidation validator="MaxAmount"/>
            <formLevelValidation validator="Image"/>
            <formLevelValidation validator="Auction"/>
            <associativeValidators>
                <validator name="MaxAmount" relationship="AND">
                    <component name="maxBid"/>
                    <associativeMessage nlsid="Max bid amount must be numeric value" isKey="false"/>
                </validator>
                <validator name="Image" relationship="AND">
                    <component name="imageId"/>
                    <associativeMessage nlsid="Image is required" isKey="false"/>
                </validator>
                <validator name="Auction" relationship="AND">
                    <component name="auctionId"/>
                    <associativeMessage nlsid="Auction is required" isKey="false"/>
                </validator>
            </associativeValidators>
            <elements>
                <element name="maxBid" pattern="[\d]+">
                    <message nlsid="Max bid amount is required" isKey="false"/>
                </element>
                <element name="imageId" pattern="[\d]+">
                    <message nlsid="Image is required" isKey="false"/>
                </element>
                <element name="auctionId" pattern="[\d]+">
                    <message nlsid="Auction is required" isKey="false"/>
                </element>
            </elements>
        </form>
        <form name="placeBidConfirmForm">
            <formLevelValidation validator="MaxAmount"/>
            <formLevelValidation validator="Domain"/>
            <formLevelValidation validator="Image"/>
            <formLevelValidation validator="Auction"/>
            <associativeValidators>
                <validator name="MaxAmount" relationship="AND">
                    <component name="maxBid"/>
                    <associativeMessage nlsid="Max bid amount must be numeric value" isKey="false"/>
                </validator>
                <validator name="Domain" relationship="AND">
                    <component name="domainId"/>
                    <associativeMessage nlsid="Domain is required" isKey="false"/>
                </validator>
                <validator name="Image" relationship="AND">
                    <component name="imageId"/>
                    <associativeMessage nlsid="Image is required" isKey="false"/>
                </validator>
                <validator name="Auction" relationship="AND">
                    <component name="auctionId"/>
                    <associativeMessage nlsid="Auction is required" isKey="false"/>
                </validator>
            </associativeValidators>
            <elements>
                <element name="maxBid" pattern="[\d]+">
                    <message nlsid="Max bid amount is required" isKey="false"/>
                </element>
                <element name="domainId" pattern="[\d]+">
                    <message nlsid="Domain is required" isKey="false"/>
                </element>
                <element name="imageId" pattern="[\d]+">
                    <message nlsid="Image is required" isKey="false"/>
                </element>
                <element name="auctionId" pattern="[\d]+">
                    <message nlsid="Auction is required" isKey="false"/>
                </element>
            </elements>
        </form>
        <form name="updateBidForm">
            <formLevelValidation validator="MaxAmount"/>
            <formLevelValidation validator="Bid"/>
            <formLevelValidation validator="Auction"/>
            <associativeValidators>
                <validator name="MaxAmount" relationship="AND">
                    <component name="maxBid"/>
                    <associativeMessage nlsid="Max bid amount must be numeric value" isKey="false"/>
                </validator>
                <validator name="Bid" relationship="AND">
                    <component name="bidId"/>
                    <associativeMessage nlsid="Bid is required" isKey="false"/>
                </validator>
                <validator name="Auction" relationship="AND">
                    <component name="auctionId"/>
                    <associativeMessage nlsid="Auction is required" isKey="false"/>
                </validator>
            </associativeValidators>
            <elements>
                <element name="maxBid" pattern="[\d]+">
                    <message nlsid="Max bid amount is required" isKey="false"/>
                </element>
                <element name="bidId" pattern="[\d]+">
                    <message nlsid="Bid is required" isKey="false"/>
                </element>
                <element name="auctionId" pattern="[\d]+">
                    <message nlsid="Auction is required" isKey="false"/>
                </element>
            </elements>
        </form>
        <form name="updateBidConfirmForm">
            <formLevelValidation validator="MaxAmount"/>
